INSERT INTO estados VALUES ('AC','Acre');
INSERT INTO estados VALUES ('AL','Alagoas');
INSERT INTO estados VALUES ('AM','Amazonas');
INSERT INTO estados VALUES ('AP','Amapá');
INSERT INTO estados VALUES ('BA','Bahia');
INSERT INTO estados VALUES ('CE','Ceará');
INSERT INTO estados VALUES ('DF','Distrito Federal');
INSERT INTO estados VALUES ('ES','Espírito Santo');
INSERT INTO estados VALUES ('GO','Goiás');
INSERT INTO estados VALUES ('MA','Maranhão');
INSERT INTO estados VALUES ('MG','Minas Gerais');
INSERT INTO estados VALUES ('MS','Mato Grosso do Sul');
INSERT INTO estados VALUES ('MT','Mato Grosso');
INSERT INTO estados VALUES ('PA','Pará');
INSERT INTO estados VALUES ('PB','Paraíba');
INSERT INTO estados VALUES ('PE','Pernambuco');
INSERT INTO estados VALUES ('PI','Piauí');
INSERT INTO estados VALUES ('PR','Paraná');
INSERT INTO estados VALUES ('RJ','Rio de Janeiro');
INSERT INTO estados VALUES ('RN','Rio Grande do Norte');
INSERT INTO estados VALUES ('RO','Rondônia');
INSERT INTO estados VALUES ('RR','Roraima');
INSERT INTO estados VALUES ('RS','Rio Grande do Sul');
INSERT INTO estados VALUES ('SC','Santa Catarina');
INSERT INTO estados VALUES ('SE','Sergipe');
INSERT INTO estados VALUES ('SP','São Paulo');
INSERT INTO estados VALUES ('TO','Tocantins');
